# Generated by Django 5.2.1 on 2025-05-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chunks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
