# Generated by Django 5.2.4 on 2025-07-26 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_code_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='quiz',
            field=models.ForeignKey(blank=True, help_text='Quizs associated with this module', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.quiz'),
        ),
    ]
