# Generated by Django 5.2.4 on 2025-07-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_module_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='quiz',
        ),
        migrations.AddField(
            model_name='module',
            name='quiz',
            field=models.ManyToManyField(blank=True, help_text='Quizs associated with this module', null=True, related_name='modules', to='core.quiz'),
        ),
    ]
