# Generated by Django 5.2.4 on 2025-08-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_flashcardset_summary_transcript'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcardset',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transcript',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='document',
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='transcripts/'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='media_url',
            field=models.URLField(blank=True, help_text='URL of the media file, thi swill be filled in case for a youtube video', null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='module',
            field=models.ManyToManyField(blank=True, null=True, related_name='transcripts', to='core.module'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
