# Generated by Django 5.2.4 on 2025-08-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_flashcardset_options_alter_transcript_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='module',
            field=models.ManyToManyField(blank=True, related_name='transcripts', to='core.module'),
        ),
    ]
