# Generated by Django 5.2.4 on 2025-08-02 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_studyevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyevent',
            name='date',
        ),
        migrations.RemoveField(
            model_name='studyevent',
            name='time',
        ),
        migrations.AddField(
            model_name='studyevent',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
