# Generated by Django 5.2.4 on 2025-08-03 09:02

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_studyevent_date_remove_studyevent_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcardset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transcript',
            options={},
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='title',
            field=models.CharField(blank=True, db_index=True, help_text='Title of the flashcard set', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='snippet',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='First 100 chars of the summary for quick search', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='title',
            field=models.CharField(blank=True, db_index=True, help_text='Title of the summary', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='title',
            field=models.CharField(blank=True, db_index=True, help_text='Title of the transcript set', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.JSONField(help_text='Quiz questions in JSON format'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_title',
            field=models.CharField(blank=True, db_index=True, help_text='Title of the quiz', max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='flashcardset',
            index=django.contrib.postgres.indexes.GinIndex(fields=['cards'], name='flashcards_cards_gin', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=django.contrib.postgres.indexes.GinIndex(fields=['questions'], name='quiz_questions_gin', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddIndex(
            model_name='summary',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content'], name='summary_content_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=django.contrib.postgres.indexes.GinIndex(fields=['transcript'], name='transcript_body_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
