# Generated by Django 5.2.4 on 2025-08-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_flashcardset_options_alter_transcript_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
